apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uir39md80-go 
  janus-idp.io/tekton: uir39md80-go
  backstage.io/kubernetes-id: uir39md80-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uir39md80-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml