apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uir39md80-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uir39md80-go 
  name: uir39md80-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uir39md80-go 
